import assert from "node:assert/strict";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";

const port = 3022;
const databasePath = `apps/api/data/worker-contract-${process.pid}.db`;
const storageDir = path.resolve(`data/worker-resources-${process.pid}`);
fs.mkdirSync("apps/api/data", { recursive: true });
fs.closeSync(fs.openSync(databasePath, "w"));
const env = { ...process.env, API_PORT: String(port), DATABASE_URL: "file:./" + databasePath, RESOURCE_STORAGE_DIR: storageDir, WORKER_POLL_INTERVAL_MS: "50" };
const api = spawn(process.execPath, ["apps/api/src/nest.js"], { env, stdio: "ignore" });
let worker;
const base = `http://127.0.0.1:${port}`;
const waitForHealth = async () => { for (let i = 0; i < 200; i += 1) { try { if ((await fetch(`${base}/health`)).ok) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("API did not start"); };
const json = async (url, options) => { const response = await fetch(`${base}${url}`, options); return { response, body: response.status === 204 ? {} : await response.json() }; };
const waitFor = async (fn, allowed = ["succeeded", "failed"], timeout = 15_000) => { const end = Date.now() + timeout; let value; while (Date.now() < end) { value = await fn(); if (allowed.includes(value?.status)) return value; await new Promise((resolve) => setTimeout(resolve, 100)); } return value; };
const postTask = async (type) => (await json("/api/tasks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type }) })).body;

try {
  await waitForHealth();
  const interrupted = await postTask("demo_success");
  const setup = new Database(databasePath); const interruptedAt = new Date().toISOString();
  setup.prepare("UPDATE tasks SET status='running',worker_id='dead-worker',started_at=?,updated_at=?,retry_count=0 WHERE id=?").run(interruptedAt, interruptedAt, interrupted.data.id);
  setup.prepare("INSERT INTO task_attempts (id,task_id,attempt_number,status,worker_id,started_at) VALUES (?,?,1,'running','dead-worker',?)").run(crypto.randomUUID(), interrupted.data.id, interruptedAt);
  setup.close();
  worker = spawn(process.execPath, ["apps/worker/src/index.js"], { env, stdio: "ignore" });
  const success = await postTask("demo_success");
  const failure = await postTask("demo_failure");
  const retryable = await postTask("demo_retryable");
  const kb = await json("/api/knowledge-bases", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Worker KB" }) });
  const sourceText = "# Worker\n\nraretermxyz appears once " + "context ".repeat(1800);
  const imported = await json("/api/resources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "worker.md", content: sourceText, knowledgeBaseId: kb.body.data.id }) });
  assert.equal(imported.response.status, 201);
  const read = async (id) => (await json(`/api/tasks/${id}`)).body.data;
  assert.equal((await waitFor(() => read(interrupted.body?.data?.id || interrupted.data.id))).status, "succeeded");
  assert.equal((await waitFor(() => read(success.data.id))).status, "succeeded");
  assert.equal((await waitFor(() => read(failure.data.id))).status, "failed");
  const taskRetry = await json(`/api/tasks/${failure.data.id}/retry`, { method: "POST" }); assert.equal(taskRetry.response.status, 202); assert.notEqual(taskRetry.body.data.id, failure.data.id); assert.equal((await waitFor(() => read(taskRetry.body.data.id))).status, "failed");
  const retryableTask = await waitFor(() => read(retryable.data.id), ["failed"], 15_000); assert.equal(retryableTask.status, "failed"); assert.equal(retryableTask.retryCount, 3);
  const resource = async () => (await json(`/api/resources/${imported.body.data.resource.id}`)).body.data;
  const indexed = await waitFor(resource, ["indexed"], 15_000); assert.equal(indexed.status, "indexed");
  const search = await json(`/api/search?q=raretermxyz&knowledgeBaseId=${kb.body.data.id}`); assert.equal(search.body.data.length, 1); assert.equal(search.body.data[0].chunk_type, "text"); assert.ok(search.body.data[0].parent_content);
  const runs = await json(`/api/resources/${imported.body.data.resource.id}/processing-runs`); assert.equal(runs.body.data.length, 1); assert.equal(runs.body.data[0].status, "indexed");
  const artifact = await json(`/api/resources/${imported.body.data.resource.id}/processing-runs/${runs.body.data[0].id}/canonical`); assert.equal(artifact.body.data.resourceVersionId, imported.body.data.version.id); assert.ok(artifact.body.data.blocks.length >= 1);
  const sourceDb = new Database(databasePath); const sourceRow = sourceDb.prepare("SELECT storage_key FROM resource_versions WHERE id=?").get(imported.body.data.version.id); sourceDb.close(); const sourcePath = path.join(storageDir, sourceRow.storage_key); const sourceBytes = fs.readFileSync(sourcePath); fs.writeFileSync(sourcePath, Buffer.from([0xff, 0xfe, 0xfd]));
  const failedReprocess = await json(`/api/resources/${imported.body.data.resource.id}/reprocess`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ versionId: imported.body.data.version.id }) }); assert.equal(failedReprocess.response.status, 202); assert.equal((await waitFor(() => read(failedReprocess.body.data.id))).status, "failed"); assert.equal((await resource()).status, "indexed"); const preservedSearch = await json(`/api/search?q=raretermxyz&resourceVersionId=${encodeURIComponent(imported.body.data.version.id)}`); assert.equal(preservedSearch.body.data.length, 1); fs.writeFileSync(sourcePath, sourceBytes);
  const newVersion = await json(`/api/resources/${imported.body.data.resource.id}/versions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content: "# New\n\nfreshtermabc" }) }); assert.equal(newVersion.response.status, 201);
  const versionDeadline = Date.now() + 15_000; let afterVersion = await resource(); while (Date.now() < versionDeadline && afterVersion.currentVersion?.id !== newVersion.body.data.version.id) { await new Promise((resolve) => setTimeout(resolve, 100)); afterVersion = await resource(); } assert.equal(afterVersion.currentVersion.id, newVersion.body.data.version.id);
  const oldSearch = await json(`/api/search?q=raretermxyz&knowledgeBaseId=${kb.body.data.id}`); assert.equal(oldSearch.body.data.length, 0);
  const historySearch = await json(`/api/search?q=raretermxyz&resourceVersionId=${encodeURIComponent(imported.body.data.version.id)}`); assert.equal(historySearch.body.data.length, 1);
  const reprocess = await json(`/api/resources/${imported.body.data.resource.id}/reprocess`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ versionId: imported.body.data.version.id }) }); assert.equal(reprocess.response.status, 202);
  await waitFor(() => read(reprocess.body.data.id), ["succeeded"], 15_000);
  const historyAfterReprocess = await json(`/api/search?q=raretermxyz&resourceVersionId=${encodeURIComponent(imported.body.data.version.id)}`); assert.equal(historyAfterReprocess.body.data.length, 1);
  const currentAfterHistoryReprocess = await resource(); assert.equal(currentAfterHistoryReprocess.currentVersion.id, newVersion.body.data.version.id);
  const runsAfterReprocess = await json(`/api/resources/${imported.body.data.resource.id}/processing-runs`); assert.equal(runsAfterReprocess.body.data.filter((run) => run.resource_version_id === imported.body.data.version.id && run.status === "indexed").length, 1);
  const rebuild = await json("/api/resources/rebuild", { method: "POST" }); assert.equal(rebuild.body.data.mode, "build-then-swap"); assert.ok(rebuild.body.data.queued >= 2);
  const failureBytes = Buffer.from([0xff, 0xfe, 0xfd]); const form = new FormData(); form.set("name", "broken.txt"); form.set("knowledgeBaseId", kb.body.data.id); form.set("file", new Blob([failureBytes], { type: "text/plain" }), "broken.txt");
  const broken = await json("/api/resources", { method: "POST", body: form }); const brokenResourceId = broken.body.data.resource.id; const brokenTask = await waitFor(() => json(`/api/resources/${brokenResourceId}`).then((result) => result.body.data.task), ["failed"], 15_000); assert.equal(brokenTask.status, "failed"); assert.equal((await json(`/api/resources/${brokenResourceId}`)).body.data.status, "failed");
  const genericRetry = await json(`/api/tasks/${brokenTask.id}/retry`, { method: "POST" }); assert.equal(genericRetry.response.status, 202); assert.notEqual((await json(`/api/resources/${brokenResourceId}`)).body.data.status, "failed"); assert.equal((await waitFor(() => json(`/api/tasks/${genericRetry.body.data.id}`).then((result) => result.body.data))).status, "failed");
  const retry = await json(`/api/resources/${brokenResourceId}/retry`, { method: "POST" }); assert.equal(retry.response.status, 202); assert.notEqual(retry.body.data.id, brokenTask.id);
  const sqlite = new Database(databasePath);
  assert.ok(sqlite.prepare("SELECT COUNT(*) AS n FROM task_attempts").get().n >= 6);
  assert.equal(sqlite.prepare("SELECT worker_id FROM tasks WHERE id=?").get(success.data.id).worker_id, null);
  assert.equal(sqlite.prepare("SELECT worker_id FROM tasks WHERE id=?").get(failure.data.id).worker_id, null);
  assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM task_attempts WHERE task_id=?").get(interrupted.data.id).n, 2);
  assert.ok(sqlite.prepare("SELECT COUNT(*) AS n FROM chunks WHERE resource_version_id=? AND status='superseded'").get(imported.body.data.version.id).n >= 1);
  assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM resource_fts").get().n, sqlite.prepare("SELECT COUNT(*) AS n FROM chunks WHERE chunk_type='text' AND status='active'").get().n);
  sqlite.close();
  console.log("worker contract self-check passed");
} finally { api.kill(); worker?.kill(); }
